# Generated by Django 6.0.7 on 2026-07-17 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(db_index=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('source_module', models.CharField(blank=True, max_length=100)),
                ('title_ar', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('snapshot_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-alert_time'],
            },
        ),
        migrations.CreateModel(
            name='KpiDailySnapshot',
            fields=[
                ('snapshot_date', models.DateField(primary_key=True, serialize=False)),
                ('mapped_units_count', models.PositiveIntegerField(default=0)),
                ('active_alerts_count', models.PositiveIntegerField(default=0)),
                ('layers_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='computed', max_length=20)),
                ('built_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('notes_ar', models.TextField(blank=True)),
                ('notes_en', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geology_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='OperationalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('governorate', 'Governorate'), ('site', 'Site')], default='national', max_length=20)),
                ('scope_code', models.CharField(blank=True, default='', max_length=100)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('label_ar', models.CharField(blank=True, max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start', 'metric_key'],
                'constraints': [models.UniqueConstraint(fields=('metric_key', 'scope_type', 'scope_code', 'period_type', 'period_start'), name='geology_unique_operational_target')],
            },
        ),
    ]
