# Generated by Django 6.0.7 on 2026-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0002_daily_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='OreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('production_type', models.CharField(blank=True, default='', max_length=64)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
