# Generated by Django 6.0.4 on 2026-06-17 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0004_recalculate_project_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetUserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_users', to='project_budget.foundation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_scope', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
