# Generated by Django 6.0.4 on 2026-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0005_budgetuserscope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='allocated_amount',
            new_name='Approved_budget',
        ),
        migrations.AddField(
            model_name='project',
            name='Budget_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='project',
            name='Proposed_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
