# Generated by Django 6.0.4 on 2026-06-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0009_policy_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['name_ar', 'id']},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['name_ar', 'id']},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='project',
        ),
        migrations.RemoveField(
            model_name='target',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='project_budget.policy'),
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='project_budget.target'),
        ),
    ]
