# Generated by Django 5.1.6 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_budget", "0012_measureunit_project_quantitative_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcategory",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20),
        ),
    ]
