# Generated by Django 6.0.4 on 2026-07-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0014_replacement_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
