# Generated by Django 6.0.4 on 2026-07-11 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('project_budget', '0015_project_completion_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_projects', to='locations.community'),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_projects', to='locations.district'),
        ),
        migrations.AddField(
            model_name='project',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_projects', to='locations.governorate'),
        ),
        migrations.AddField(
            model_name='project',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_projects', to='locations.subdistrict'),
        ),
        migrations.AlterField(
            model_name='project',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='project_budget.town'),
        ),
    ]
