# Generated by Django 5.2.15 on 2026-06-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_layers', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostGISGeometryColumns',
        ),
        migrations.DeleteModel(
            name='PostGISSpatialRefSys',
        ),
    ]
