# Generated by Django 6.0.7 on 2026-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map_layers', '0005_electricity_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisElectricityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gis_electricity_feature',
                'ordering': ['name', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GisWaterFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gis_water_feature',
                'ordering': ['name', 'id'],
                'managed': False,
            },
        ),
    ]
