# Generated by Django 5.2.1 on 2026-06-04 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('notes_ar', models.TextField(blank=True)),
                ('notes_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_gas_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('dimension', models.CharField(blank=True, default='', max_length=32)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='oil_gas.dailyreport')),
            ],
            options={
                'ordering': ['metric_key', 'dimension'],
                'indexes': [models.Index(fields=['metric_key', 'report'], name='oil_gas_dai_metric__f2582b_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'metric_key', 'dimension'), name='oil_gas_unique_metric_per_report')],
            },
        ),
    ]
