# Generated by Django 5.2.1 on 2026-06-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_gas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(db_index=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('source_module', models.CharField(blank=True, max_length=100)),
                ('title_ar', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('snapshot_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-alert_time'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_date', models.DateField(db_index=True)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('crude_bbl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('revenue_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['-export_date'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('oil', 'Oil'), ('gas', 'Gas')], max_length=20)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('operator_company', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('shutdown', 'Shutdown'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('design_capacity_bpd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='FuelConsumptionBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50, unique=True)),
                ('daily_consumption', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit', models.CharField(default='ton', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='KpiDailySnapshot',
            fields=[
                ('snapshot_date', models.DateField(primary_key=True, serialize=False)),
                ('total_oil_production_bpd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_gas_production_mmscf', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('refinery_utilization_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gasoline_stock_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diesel_stock_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gas_supply_to_power_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_export_bbl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('export_revenue_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_losses_bbl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('active_alerts_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='computed', max_length=20)),
                ('built_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_location', models.CharField(blank=True, max_length=200)),
                ('destination_location', models.CharField(blank=True, max_length=200)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('design_capacity_bpd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('degraded', 'Degraded'), ('shutdown', 'Shutdown')], default='normal', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Refinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refinery_name', models.CharField(max_length=200)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('operating', 'Operating'), ('stopped', 'Stopped'), ('maintenance', 'Maintenance')], default='operating', max_length=20)),
                ('design_capacity_bpd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'verbose_name_plural': 'refineries',
                'ordering': ['refinery_name'],
            },
        ),
        migrations.CreateModel(
            name='StorageFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'storage facilities',
                'ordering': ['facility_name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateTimeField(db_index=True)),
                ('incident_type', models.CharField(max_length=100)),
                ('estimated_loss_bbl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='oil_gas.pipeline')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='PowerGasRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_station', models.CharField(max_length=200)),
                ('requirement_date', models.DateField(db_index=True)),
                ('required_mmscf', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'ordering': ['-requirement_date'],
                'constraints': [models.UniqueConstraint(fields=('power_station', 'requirement_date'), name='oil_gas_unique_power_gas_requirement')],
            },
        ),
        migrations.CreateModel(
            name='PowerGasSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField(db_index=True)),
                ('power_station', models.CharField(max_length=200)),
                ('supplied_mmscf', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['-supply_date'],
                'constraints': [models.UniqueConstraint(fields=('supply_date', 'power_station'), name='oil_gas_unique_power_gas_supply')],
            },
        ),
        migrations.CreateModel(
            name='ProductionLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_date', models.DateField(db_index=True)),
                ('loss_type', models.CharField(max_length=100)),
                ('estimated_loss_bbl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_losses', to='oil_gas.field')),
            ],
            options={
                'ordering': ['-loss_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(db_index=True)),
                ('crude_oil_bbl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('natural_gas_mmscf', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('condensate_bbl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('water_cut_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('operating_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production', to='oil_gas.field')),
            ],
            options={
                'ordering': ['-production_date'],
                'constraints': [models.UniqueConstraint(fields=('field', 'production_date'), name='oil_gas_unique_field_production_date')],
            },
        ),
        migrations.CreateModel(
            name='RefineryDailyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(db_index=True)),
                ('gasoline_ton', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diesel_ton', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fuel_oil_ton', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('lpg_ton', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('refinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_outputs', to='oil_gas.refinery')),
            ],
            options={
                'ordering': ['-production_date'],
                'constraints': [models.UniqueConstraint(fields=('refinery', 'production_date'), name='oil_gas_unique_refinery_output_date')],
            },
        ),
        migrations.CreateModel(
            name='FuelInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField(db_index=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('current_volume', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('max_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='oil_gas.storagefacility')),
            ],
            options={
                'verbose_name_plural': 'fuel inventories',
                'ordering': ['-inventory_date'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'inventory_date', 'fuel_type'), name='oil_gas_unique_fuel_inventory')],
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_code', models.CharField(max_length=100)),
                ('well_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('production_capacity_bpd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='oil_gas.field')),
            ],
            options={
                'ordering': ['well_code'],
                'constraints': [models.UniqueConstraint(fields=('field', 'well_code'), name='oil_gas_unique_well_code')],
            },
        ),
    ]
