# Generated by Django 5.2.15 on 2026-06-05 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_gas', '0004_facility_generalization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationaltarget',
            new_name='oil_gas_ope_scope_t_757fe2_idx',
            old_name='oil_gas_oper_scope_idx',
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='export',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='export',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('storage_depot', 'Storage depot'), ('power_plant', 'Power plant'), ('substation', 'Substation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refinerydailyoutput',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='refinerydailyoutput',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
