# Generated by Django 5.2.14 on 2026-07-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil_gas', '0008_refresh_refinery_alert_titles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipelineIncident',
        ),
    ]
