# Generated by Django 6.0.7 on 2026-07-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_gas', '0010_clear_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='path_coordinates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='refinery',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='well',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='well',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
