# Generated by Django 6.0.7 on 2026-07-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil_gas', '0011_map_geojson_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='design_capacity_mw',
        ),
    ]
