# Generated by Django 5.2.15 on 2026-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('governorate_pcode', models.CharField(db_index=True, max_length=16)),
                ('governorate_name_en', models.CharField(max_length=128)),
                ('governorate_name_ar', models.CharField(blank=True, max_length=128)),
                ('organization_slug', models.CharField(blank=True, max_length=64)),
                ('organization_acronym', models.CharField(blank=True, max_length=32)),
                ('organization_name_en', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(choices=[('oil-gas', 'Oil & Gas'), ('water-resources', 'Water Resources'), ('electricity', 'Electricity')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('completed', 'Completed')], default='active', max_length=16)),
                ('budget_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_spent_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reporting_through', models.DateField(blank=True, null=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
