# Generated by Django 5.2.15 on 2026-06-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_csv_schema'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='developmentproject',
            table='projects_developmentproject',
        ),
    ]
