# Generated by Django 5.2.15 on 2026-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_developmentproject_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/logos/'),
        ),
    ]
