# Generated by Django 6.0.7 on 2026-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectorganization_governorate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBudgetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('percentage_completion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('proposed_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'project_budget_project',
                'ordering': ['-created_at', 'id'],
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReportDynamicFormsAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, default='', max_length=255)),
                ('key', models.CharField(blank=True, default='', max_length=128)),
                ('type', models.CharField(max_length=50)),
                ('title_id', models.IntegerField(blank=True, null=True)),
                ('is_measure', models.BooleanField(default=False)),
                ('measure_order', models.PositiveIntegerField(default=1)),
                ('unit_ar', models.CharField(blank=True, default='', max_length=64)),
                ('unit_en', models.CharField(blank=True, default='', max_length=64)),
                ('decimals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('measure_status_rule', models.CharField(blank=True, default='', max_length=64)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dynamic_forms_attribute',
                'ordering': ['id'],
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReportDynamicFormsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.IntegerField()),
                ('sub_main_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField()),
                ('confirmed', models.CharField(max_length=10)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('row_key', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dynamic_forms_info',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReportDynamicFormsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=128)),
                ('order', models.PositiveIntegerField(default=1)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dynamic_forms_title',
                'ordering': ['category_id', 'order', 'id'],
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReportDynamicFormsTitleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'dynamic_forms_titlecategory',
                'ordering': ['order', 'id'],
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReportFoundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_budget_foundation',
                'ordering': ['name_ar', 'id'],
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReportGovernorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'locations_governorate',
                'ordering': ['name_ar', 'id'],
                'managed': False,
            },
            bases=(models.Model,),
        ),
    ]
