# Generated by Django 6.0.7 on 2026-08-29 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import accounts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False, help_text='Full portal admin: all sectors, control panel, user management.')),
                ('can_view_oil_gas', models.BooleanField(default=False)),
                ('can_write_oil_gas', models.BooleanField(default=False)),
                ('can_view_electricity', models.BooleanField(default=False)),
                ('can_write_electricity', models.BooleanField(default=False)),
                ('can_view_water', models.BooleanField(default=False)),
                ('can_write_water', models.BooleanField(default=False)),
                ('can_view_mineral', models.BooleanField(default=False)),
                ('can_write_mineral', models.BooleanField(default=False)),
                ('can_manage_projects', models.BooleanField(default=False)),
                ('can_manage_datasets', models.BooleanField(default=False)),
                ('can_manage_control_panel', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('can_write_info', models.BooleanField(default=False)),
                ('can_view_info', models.BooleanField(default=False)),
                ('can_confirm_info', models.BooleanField(default=False)),
                ('can_export_reports', models.BooleanField(default=False)),
                ('can_add_user', models.BooleanField(default=False)),
                ('can_view_budget', models.BooleanField(default=False)),
                ('can_write_budget', models.BooleanField(default=False)),
                ('can_manage_budget_users', models.BooleanField(default=False)),
                ('can_manage_budget', models.BooleanField(default=False, help_text='Full budget-module admin (all foundations); not Django staff.')),
                ('can_manage_reference_data', models.BooleanField(default=False, help_text='CRUD on budget reference-data tabs (categories, companies, etc.).')),
                ('deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
