# Generated by Django 6.0.7 on 2026-09-06

from django.db import migrations, models


SECTOR_BOOLS = ('water', 'electricity', 'oil_gas', 'mineral')


def backfill_portal_sectors(apps, schema_editor):
    """Seed portal_sectors from the existing per-sector booleans, and lift
    can_view_info / can_write_info to match so the recompute in
    User.apply_portal_sectors() reproduces each user's current portal access."""
    User = apps.get_model('accounts', 'User')
    for u in User.objects.all().iterator():
        sectors = [
            s for s in SECTOR_BOOLS
            if getattr(u, f'can_view_{s}') or getattr(u, f'can_write_{s}')
        ]
        if u.can_manage_projects:
            sectors.append('projects')
        had_view = any(
            getattr(u, f'can_view_{s}') or getattr(u, f'can_write_{s}')
            for s in SECTOR_BOOLS
        )
        had_write = any(getattr(u, f'can_write_{s}') for s in SECTOR_BOOLS)
        fields = ['portal_sectors']
        u.portal_sectors = sectors
        if had_view and not u.can_view_info:
            u.can_view_info = True
            fields.append('can_view_info')
        if had_write and not u.can_write_info:
            u.can_write_info = True
            fields.append('can_write_info')
        u.save(update_fields=fields)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unify_user_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal_sectors',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='moeds portal sectors, subset of User.PORTAL_SECTORS.',
            ),
        ),
        migrations.RunPython(backfill_portal_sectors, noop),
    ]
