export const PROJECT_CHANGE_LOG_FIELD_OPTIONS = [
  { value: 'status', label: 'budget.projects.fields.status' },
  { value: 'approved_budget', label: 'budget.projects.fields.approved_budget' },
  { value: 'budget_expenditure', label: 'budget.projects.fields.budget_expenditure' },
  { value: 'percentage_completion', label: 'budget.projects.fields.percentage_completion' },
  { value: 'end_date', label: 'budget.projects.fields.end_date' },
  { value: 'name_ar', label: 'budget.projects.fields.name_ar' },
  { value: 'name_en', label: 'budget.projects.fields.name_en' },
  { value: 'annual_budget', label: 'budget.projects.fields.annual_budget' },
  { value: 'foundation', label: 'budget.projects.fields.foundation' },
  { value: 'community', label: 'budget.projects.fields.community' },
  { value: 'previous_project', label: 'budget.projects.fields.previous_project' },
  { value: 'is_round', label: 'budget.projects.fields.is_round' },
  { value: 'latitude', label: 'budget.projects.fields.latitude' },
  { value: 'longitude', label: 'budget.projects.fields.longitude' },
  { value: 'completion_is_manual', label: 'budget.projects.fields.completion_is_manual' },
  { value: 'proposed_budget', label: 'budget.projects.fields.proposed_budget' },
  { value: 'description', label: 'budget.projects.fields.description' },
  { value: 'start_date', label: 'budget.projects.fields.start_date' },
  { value: 'target', label: 'budget.projects.fields.target' },
  { value: 'policy', label: 'budget.projects.fields.policy' },
  { value: 'quantitative_target_value', label: 'budget.projects.fields.quantitative_target_value' },
  { value: 'quantitative_target_unit', label: 'budget.projects.fields.quantitative_target_unit' },
];
