# Generated by Django 5.2.13 on 2026-06-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_title_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['order', 'id']},
        ),
        # User.can_export_reports now lives on accounts.User
    ]
