# Generated by Django 6.0.4 on 2026-06-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0008_info_row_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='info',
            name='dynamic_for_row_key_sub_idx',
        ),
    ]
