# Generated by Django 6.0.4 on 2026-06-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0009_remove_info_dynamic_for_row_key_sub_idx'),
    ]

    operations = [
        # Budget RBAC flags moved to accounts.User
    ]
