# Generated by Django 6.0.4 on 2026-06-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0010_user_can_manage_budget_users_user_can_view_budget_and_more'),
    ]

    operations = [
        # can_manage_budget moved to accounts.User
    ]
