# Generated by Django 6.0.7 on 2026-08-19 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0021_info_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submainsection',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['category_id', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_measure',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attribute',
            name='measure_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attribute',
            name='measure_status_rule',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit_en',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='title',
            name='code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='title',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean/Checkbox'), ('select', 'Dropdown'), ('city', 'City / Governorate'), ('district', 'District'), ('sub_district', 'Sub-district'), ('community', 'Community'), ('image', 'Image upload'), ('file', 'File upload'), ('drinking_station', 'Drinking water station'), ('dam', 'Dam'), ('rainfall_station', 'Rainfall station'), ('rainfall_basin', 'Rainfall basin'), ('spring', 'Spring'), ('lake', 'Lake'), ('river', 'River'), ('stream', 'Stream'), ('geology_unit', 'Geology unit'), ('ore_product', 'Ore product'), ('power_plant', 'Power plant'), ('substation', 'Substation'), ('transmission_line', 'Transmission line'), ('power_gis_substation_66', 'GIS substation 66 kV'), ('power_gis_substation_230', 'GIS substation 230 kV'), ('power_gis_substation_400', 'GIS substation 400 kV'), ('power_gis_renewable', 'Renewable energy site (GIS)'), ('fuel_tank_station', 'Fuel tank station'), ('hydro_dam', 'Hydro dam (daily report)'), ('load_governorate', 'Load governorate'), ('oil_field', 'Oil/gas field'), ('oil_well', 'Oil/gas well'), ('oil_refinery', 'Refinery'), ('fuel_station', 'Fuel station'), ('storage_depot', 'Storage depot'), ('pipeline', 'Pipeline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mainsection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submainsection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='title',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='dynamic_forms_title_code_unique'),
        ),
    ]
