# Generated by Django 6.0.7 on 2026-08-19 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0022_schema_contract_and_measure_catalog'),
        ('locations', '0002_community_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='info',
            index=models.Index(fields=['row_key', 'attribute'], name='dyn_info_rowkey_attr_idx'),
        ),
    ]
