# Generated by Django 6.0.7 on 2026-08-19 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0023_info_dyn_info_rowkey_attr_idx'),
        ('locations', '0002_community_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='info',
            constraint=models.UniqueConstraint(fields=('attribute', 'row_key'), name='dyn_info_attr_rowkey_unique'),
        ),
    ]
