# Generated by Django 6.0.7 on 2026-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0024_info_dyn_info_attr_rowkey_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_report_date',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='info',
            name='is_report_date',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
