# Generated by Django 6.0.7 on 2026-08-30 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0026_backfill_report_date_flag'),
        ('locations', '0002_community_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='info',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False), ('confirmed__in', ['waiting', 'accept']), ('is_report_date', True)), fields=('attribute', 'sub_main', 'value', 'entity_type', 'entity_id'), name='dyn_info_report_date_unique', nulls_distinct=False),
        ),
    ]
