# Generated by Django 6.0.7 on 2026-09-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0029_info_skew_aware_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoRow',
            fields=[
                ('row_key', models.UUIDField(primary_key=True, serialize=False)),
                ('title_category_id', models.IntegerField(blank=True, null=True)),
                ('main_section_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('first_created_at', models.DateTimeField()),
                ('latest_created_at', models.DateTimeField()),
                ('field_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('all_accepted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('loc_governorate_id', models.IntegerField(blank=True, null=True)),
                ('loc_district_id', models.IntegerField(blank=True, null=True)),
                ('loc_subdistrict_id', models.IntegerField(blank=True, null=True)),
                ('loc_community_id', models.IntegerField(blank=True, null=True)),
                ('sub_main', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_rows', to='dynamic_forms.submainsection')),
                ('title', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_rows', to='dynamic_forms.title')),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'archived', '-latest_created_at', '-row_key'], name='dyn_inforow_list_idx'), models.Index(condition=models.Q(('archived', False)), fields=['title'], name='dyn_inforow_title_idx'), models.Index(fields=['title', '-report_date'], name='dyn_inforow_title_date_idx'), models.Index(condition=models.Q(('entity_type', ''), _negated=True), fields=['entity_type', 'entity_id', '-report_date'], name='dyn_inforow_entity_idx'), models.Index(fields=['title_category_id', '-latest_created_at'], name='dyn_inforow_category_idx'), models.Index(fields=['sub_main', '-latest_created_at'], name='dyn_inforow_submain_idx'), models.Index(condition=models.Q(('all_accepted', True)), fields=['archived'], name='dyn_inforow_accepted_idx')],
            },
        ),
    ]
