# Generated by Django 5.2.15 on 2026-06-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(db_index=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('source_module', models.CharField(blank=True, max_length=100)),
                ('title_ar', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('snapshot_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-alert_time'],
            },
        ),
        migrations.CreateModel(
            name='KpiDailySnapshot',
            fields=[
                ('snapshot_date', models.DateField(primary_key=True, serialize=False)),
                ('total_generation_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('peak_demand_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('supply_demand_gap_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('plant_availability_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capacity_factor_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('renewable_share_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_installed_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('active_plants_count', models.PositiveIntegerField(default=0)),
                ('target_total_generation_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('target_peak_demand_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('target_plant_availability_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active_alerts_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='computed', max_length=20)),
                ('built_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('plant_type', models.CharField(choices=[('thermal', 'Thermal'), ('hydro', 'Hydro'), ('solar', 'Solar'), ('wind', 'Wind')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('gas', 'Natural gas'), ('hfo', 'Heavy fuel oil'), ('dual', 'Dual fuel'), ('none', 'None')], default='none', max_length=20)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('operator_company', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('shutdown', 'Shutdown')], default='active', max_length=20)),
                ('installed_capacity_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('transmission', 'Transmission'), ('distribution', 'Distribution')], default='transmission', max_length=20)),
                ('voltage_kv', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('shutdown', 'Shutdown')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_location', models.CharField(blank=True, max_length=200)),
                ('destination_location', models.CharField(blank=True, max_length=200)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('voltage_kv', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('degraded', 'Degraded'), ('shutdown', 'Shutdown')], default='normal', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('peak_demand_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('energy_consumed_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('notes_ar', models.TextField(blank=True)),
                ('notes_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='OperationalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('plant', 'Plant'), ('governorate', 'Governorate')], default='national', max_length=20)),
                ('scope_code', models.CharField(blank=True, default='', max_length=100)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('label_ar', models.CharField(blank=True, max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start', 'metric_key'],
                'constraints': [models.UniqueConstraint(fields=('metric_key', 'scope_type', 'scope_code', 'period_type', 'period_start'), name='electricity_unique_operational_target')],
            },
        ),
        migrations.CreateModel(
            name='DailyGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True)),
                ('gross_generation_mwh', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('peak_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('available_capacity_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('forced_outage_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_generation', to='electricity.powerplant')),
            ],
            options={
                'ordering': ['-report_date'],
                'constraints': [models.UniqueConstraint(fields=('plant', 'report_date'), name='electricity_unique_plant_generation_date')],
            },
        ),
    ]
