# Generated by Django 5.2.15 on 2026-06-05 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('outage_type', models.CharField(default='distribution', max_length=50)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customers_affected', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
