# Generated by Django 5.2.1 on 2026-06-15 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electricity', '0003_remove_electricity_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('reference_hour', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('notes_ar', models.TextField(blank=True)),
                ('notes_en', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='GenerationIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.CharField(blank=True, max_length=64)),
                ('description_ar', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_incidents', to='electricity.dailyreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GridLineIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=255)),
                ('voltage_kv', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('action_ar', models.TextField()),
                ('action_en', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_incidents', to='electricity.dailyreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('dimension', models.CharField(blank=True, default='', max_length=32)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='electricity.dailyreport')),
            ],
            options={
                'ordering': ['metric_key', 'dimension'],
                'indexes': [models.Index(fields=['metric_key', 'report'], name='electricity_metric__7414e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'metric_key', 'dimension'), name='electricity_unique_metric_per_report')],
            },
        ),
        migrations.CreateModel(
            name='GovernorateLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate_code', models.CharField(db_index=True, max_length=32)),
                ('consumed_mw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocated_mw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorate_loads', to='electricity.dailyreport')),
            ],
            options={
                'ordering': ['governorate_code'],
                'constraints': [models.UniqueConstraint(fields=('report', 'governorate_code'), name='electricity_unique_gov_load_per_report')],
            },
        ),
        migrations.CreateModel(
            name='HydroDamReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_code', models.CharField(choices=[('euphrates', 'Euphrates (Thawra)'), ('tishreen', 'Tishreen')], max_length=32)),
                ('front_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('back_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('generation_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outflow_m3s', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydro_readings', to='electricity.dailyreport')),
            ],
            options={
                'ordering': ['dam_code'],
                'constraints': [models.UniqueConstraint(fields=('report', 'dam_code'), name='electricity_unique_hydro_per_report')],
            },
        ),
    ]
