# Generated by Django 5.2.1 on 2026-06-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallBasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name_en', models.CharField(max_length=128)),
                ('name_ar', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='RainfallStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('governorate', models.CharField(blank=True, max_length=64)),
                ('utm_x', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('utm_y', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='water.rainfallbasin')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RainfallObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(db_index=True)),
                ('precipitation_mm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='water.rainfallstation')),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='rainfallstation',
            constraint=models.UniqueConstraint(fields=('basin', 'name'), name='uniq_rainfall_station_per_basin'),
        ),
        migrations.AddIndex(
            model_name='rainfallobservation',
            index=models.Index(fields=['observation_date', 'station'], name='water_rainf_observa_894e41_idx'),
        ),
        migrations.AddConstraint(
            model_name='rainfallobservation',
            constraint=models.UniqueConstraint(fields=('station', 'observation_date'), name='uniq_rainfall_observation'),
        ),
    ]
