# Generated by Django 5.2.15 on 2026-06-09 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('governorate', models.CharField(blank=True, max_length=64)),
                ('utm_x', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('utm_y', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status_note', models.CharField(blank=True, max_length=128)),
                ('dam_type', models.CharField(blank=True, max_length=128)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_storage_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dead_storage_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('built_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['governorate', 'name'],
                'constraints': [models.UniqueConstraint(fields=('governorate', 'name'), name='uniq_dam_per_governorate')],
            },
        ),
        migrations.CreateModel(
            name='DamStorageReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(db_index=True)),
                ('storage_mcm', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='water.dam')),
            ],
            options={
                'ordering': ['-reading_date'],
                'indexes': [models.Index(fields=['reading_date', 'dam'], name='water_damst_reading_342383_idx')],
                'constraints': [models.UniqueConstraint(fields=('dam', 'reading_date'), name='uniq_dam_storage_reading')],
            },
        ),
    ]
