# Generated by Django 5.2.15 on 2026-06-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_dam_damstoragereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuphratesCascadeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(db_index=True, unique=True)),
                ('inflow_jarabulus', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tishreen_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('tishreen_storage_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tishreen_outflow', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tishreen_generation_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('furat_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('furat_storage_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('furat_outflow', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('furat_generation_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('kadiran_outflow', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('kadiran_generation_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('al_jalab_discharge', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('total_generation_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('report_label', models.CharField(blank=True, max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
    ]
