# Generated by Django 5.2.15 on 2026-07-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_rainfallbasin_area_km2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkingWaterStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tei_id', models.CharField(blank=True, max_length=64)),
                ('org_unit', models.CharField(blank=True, max_length=128)),
                ('station_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('governorate', models.CharField(blank=True, db_index=True, max_length=128)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('subdistrict', models.CharField(blank=True, max_length=128)),
                ('community', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['governorate', 'name'],
                'indexes': [models.Index(fields=['governorate', 'district'], name='water_drink_governo_144ca7_idx')],
            },
        ),
    ]
