# Generated by Django 5.2.15 on 2026-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_drinking_water_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='has_grid_power',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='is_boosting_station',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='is_filtration_station',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='is_operational',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='is_well_station',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='needs_solar_power',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
