# Generated by Django 5.2.15 on 2026-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_drinkingwaterstation_operational_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='building_condition',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='has_water_hammer_protection',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='non_operational_reason',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='previously_rehabilitated',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='rehabilitation_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='safety_procedures',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='water_hammer_efficiency',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
