# Generated by Django 5.2.15 on 2026-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_drinkingwaterstation_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='alternative_power_source',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='electrical_connection_efficiency',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='electrical_panel_efficiency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='generator_available',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='grid_connection_working',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='grid_power_productivity',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='has_public_grid_supply',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='needs_solar_installation',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='solar_power_available',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='solar_power_productivity',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='solar_space_available',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='solar_system_efficiency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='transformer_efficiency',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
