# Generated by Django 5.2.15 on 2026-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_drinkingwaterstation_power_supply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='has_water_tanks',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='is_water_analyzed',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterstation',
            name='lab_equipment_status',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
