# Generated by Django 6.0.7 on 2026-07-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_water_admin_registry_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfallbasin',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rainfallbasin',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rainfallbasin',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
