# Generated by Django 6.0.7 on 2026-07-18 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_rainfall_basin_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('dimension', models.CharField(blank=True, default='', max_length=32)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='water.dailyreport')),
            ],
            options={
                'ordering': ['metric_key', 'dimension'],
                'indexes': [models.Index(fields=['metric_key', 'report'], name='water_daily_metric__39bc19_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'metric_key', 'dimension'), name='water_unique_metric_per_report')],
            },
        ),
    ]
